version: "3.1"
services:

    mariadb:
      image: mariadb:10.6
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=${DB_DATABASE}
        - MYSQL_USER=${DB_USER}
        - MYSQL_PASSWORD=${DB_PASSWORD}
      ports:
        - "8083:3306"

    app:
      build:
        context: ../../
        dockerfile: ./deployment/dev/Dockerfile
      volumes:
        - ../..:/application
        - ./php/conf.d/99-ini-overrides.ini:/etc/php8/conf.d/99-ini-overrides.ini
        - ./php/php-fpm.d/www.ini:/etc/php8/php-fpm.d/www.ini
        - ./nginx/http.d/:/etc/nginx/http.d/
        - ./supervisord.conf:/etc/supervisor/supervisord.conf
        - ./root/.bashrc:/root/.bashrc
        - ./root/.bash_aliases:/root/.bash_aliases
        - ./root/.bash_completion:/root/.bash_completion
        - ./root/.bash_functions:/root/.bash_functions
        - ./root/.bash_profile:/root/.bash_profile
        - ./root/.vimrc:/root/.vimrc
      environment:
        - DEV_MODE=${DEV_MODE}
        - DB_HOST=${DB_HOST}
        - DB_USER=${DB_USER}
        - DB_PASSWORD=${DB_PASSWORD}
        - DB_DATABASE=${DB_DATABASE}
      ports:
        - 8080:80
