###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mariadb:
      image: mariadb:10.6
      # working_dir: /application
      # volumes:
      #   - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=${DB_DATABASE}
        - MYSQL_USER=${DB_USER}
        - MYSQL_PASSWORD=${DB_PASSWORD}
      ports:
        - "8083:3306"

    webserver:
      image: nginx:alpine
      working_dir: /application/server
      volumes:
          # - ../server/public:/application/public
          - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
        - "8080:80"

    php-fpm:
      build:
        context: ../../
        dockerfile: ./deployment/dev/php-fpm/Dockerfile
      working_dir: /application/server
      volumes:
        - ../..:/application
        - ./php-fpm/php-ini-overrides.ini:/etc/php/8.0/fpm/conf.d/99-overrides.ini
        # - ../../server/.githooks/post-commit:/application/.git/hooks/post-commit
        # - ../../server/.githooks/pre-commit:/application/.git/hooks/pre-commit
      environment:
        - DEV_MODE=${DEV_MODE}
        - DB_HOST=${DB_HOST}
        - DB_USER=${DB_USER}
        - DB_PASSWORD=${DB_PASSWORD}
        - DB_DATABASE=${DB_DATABASE}

    node:
      build:
        context: ../../
        dockerfile: ./deployment/dev/node/Dockerfile
      working_dir: /application/client
      volumes:
        - ../..:/application
        # - ../../client/.githooks/pre-commit:/application/.git/hooks/pre-commit
      ports:
        - 3001:3000
      environment:
        - CHOKIDAR_USEPOLLING=true
