version: "3.9"
services:

  node:
    depends_on:
      - php-fpm
    build:
      context: ../../
      dockerfile: ./deploy/dev/node/Dockerfile
    volumes:
      - ../..:/application
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true

  php-fpm:
    depends_on:
      - mariadb
      - webserver
    build:
      context: ../../
      dockerfile: ./deploy/dev/php/Dockerfile
    volumes:
      - ../..:/application
      - ./php/conf.d/99-ini-overrides.ini:/usr/local/etc/php/conf.d/99-ini-overrides.ini
    environment:
      - DEV_MODE=${DEV_MODE}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}

  webserver:
    image: nginx:alpine
    working_dir: /application/server
    volumes:
        - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "8080:80"

  mariadb:
    image: mariadb:10.6
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - "8083:3306"
