#!/usr/bin/env bash

SCRIPT_DIR="$(dirname "$(realpath "$0")")"

source "$SCRIPT_DIR/../../../packages/bash/ci_utils.sh"

source "$SCRIPT_DIR/../../../packages/bash/bash_utils.sh"

function style-conventions() {
  ./node_modules/.bin/standard

  add_to_summary "$?"

  add_to_try "standard"
}

function tests() {
  CI=1 npm test --silent --ci

  add_to_summary "$?"

  add_to_try "npm test --no-cache"
}

cd "$SCRIPT_DIR/../" || exit

if [ ! -d "${SCRIPT_DIR}/../node_modules" ] && [ -n "$CI" ]
then
  "$SCRIPT_DIR/setup"
fi

style-conventions &

tests &

validate-shell-scripts scripts/* &

wait

show_summary

exit "$EXIT_STATUS"
