version: "3.9"
services:

  dev:
    depends_on:
      - mariadb
    build:
      context: ../../
      args:
        PHP_VERSION: "${PHP_VERSION}"
      dockerfile: ./deploy/Dockerfile
      target: dev-env
    volumes:
      # project
      - ../..:/application
      # dotfiles
      - ./home/.bashrc:/root/.bashrc
      - ./home/.bash_aliases:/root/.bash_aliases
      - ./home/.bash_completion:/root/.bash_completion
      - ./home/.bash_functions:/root/.bash_functions
      - ./home/.bash_profile:/root/.bash_profile
      - ./home/.vimrc:/root/.vimrc
      - ~/.gitignore-global:/root/.gitignore-global
      - ~/.ssh:/root/.ssh
      - ~/.config/git/authorized_signers:/root/.config/git/authorized_signers
      # php ini settings
      - ./php/conf.d:/root/.asdf/installs/php/${PHP_VERSION}/conf.d
      # Visual Studio Code Remote Server for speed-up startups
      - vscode-server:/root/.vscode-server
    environment:
      - DEV_MODE=${DEV_MODE}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}

  mariadb:
    image: mariadb:10.6
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - "8083:3306"

volumes:
  vscode-server:
