#!/usr/bin/env bash

if [ -z "$CI" ]
then
  set -e
  set -o pipefail
fi

CODE_DIRECOTRY='src/'

SCRIPT_DIR="$(dirname "$0")"

source "$SCRIPT_DIR/../../../packages/bash/utils.sh"

cd "$SCRIPT_DIR/../"

composer update \
  --classmap-authoritative \
  --no-cache \
  --no-interaction

check_exit_status $?
print_separator

composer check-platform-reqs \
  --no-cache \
  --no-interaction

check_exit_status $?
print_separator

ecs --clear-cache

check_exit_status $?
print_separator

composer-unused

check_exit_status $?
print_separator

composer-require-checker

check_exit_status $?
print_separator

phpmnd \
  --strings \
  --include-numeric-string \
  -- $CODE_DIRECOTRY

check_exit_status $?
print_separator

phpcpd $CODE_DIRECOTRY

check_exit_status $?
print_separator

psalm \
  --threads=4 \
  --no-cache

check_exit_status $?

composer dump-autoload \
  --optimize \
  --no-cache \
  --no-interaction

if [ "$EXIT_STATUS" != "0" ]
then
  exit 1
fi
