#!/usr/bin/env bash

CODE_DIRECOTRY='src/'

SCRIPT_DIR="$(dirname $(realpath "$0"))"

source "$SCRIPT_DIR/../../../packages/bash/ci_utils.sh"

cd "$SCRIPT_DIR/../"

ci-setup "$SCRIPT_DIR"

check-conflicts &

commented-code "$CODE_DIRECOTRY" &

file-class-name "$CODE_DIRECOTRY" &

multi-classes "$CODE_DIRECOTRY" &

check-var-dump &

coding-standars &

unused-packages &

find-transitive-depndencies &

find-magic-numbers -- "$CODE_DIRECOTRY" &

find-copy-pasted-code "$CODE_DIRECOTRY" &

static-analysis &

wait

remake-autoloader

show_summary

exit $EXIT_STATUS
