#!/usr/bin/env bash

PROJECT_NAME='Consultorios'

CACHE_DIR='.cache'

OPTIONS=( $@ )
unset OPTIONS[0]

function calculateSha256() {
  sha256sum dev/$1/Dockerfile
}

cd `dirname $0`

case "${1}" in
  "dev")
    mkdir -p ${CACHE_DIR}

    for VARIABLE in node php-fpm
    do
      if [ ! -f "${CACHE_DIR}/${VARIABLE}.sum" ] || [ "$(calculateSha256 ${VARIABLE})" != "$(cat ${CACHE_DIR}/${VARIABLE}.sum)" ]
      then
        OPTIONS+=("--build")
        calculateSha256 ${VARIABLE} > ${CACHE_DIR}/${VARIABLE}.sum
      fi
    done

    # delete duplicate options
    OPTIONS=($(echo "${OPTIONS[@]}" | tr ' ' '\n' | sort -u | tr '\n' ' '))

    docker-compose --file dev/docker-compose.yml --env-file dev/.env --project-name $PROJECT_NAME up ${OPTIONS[@]}
  ;;

  "prod")
    echo 'WIP'
  ;;
  *)
    echo 'Usage: deploy dev|prod [options]

Options: docker-compose up optios, for exambple:
    -d            Detached mode.
    --build       Build images before starting containers.
'
  ;;
esac
