#!/usr/bin/env bash

# Usage: deploy dev|prod [options]
# Options: docker-compose up optios, for exambple:
#     -d            Detached mode.
#     --build       Build images before starting containers.

PROJECT_NAME='Consultorios'

CACHE_DIR='.cache'

OPTIONS=( $@ )

cd `dirname $0`

mkdir -p ${CACHE_DIR}

declare -a DOCKERFILE_FOLDERS=(
  "dev/php"
  "dev/node"
  "dev/dev-env"
)

for FOLDER in "${DOCKERFILE_FOLDERS[@]}"
do
  mkdir -p "${CACHE_DIR}/${FOLDER}"

  DOCKERFILE="${FOLDER}/Dockerfile"
  DOCKERFILE_SUM="${CACHE_DIR}/${FOLDER}/Dockerfile.sum"

  if [ ! -f "${DOCKERFILE_SUM}" ] || [ "$(sha256sum ${DOCKERFILE})" != "$(cat ${DOCKERFILE_SUM})" ]
  then
    OPTIONS+=("--build")
    sha256sum ${DOCKERFILE} > ${DOCKERFILE_SUM}
  fi
done

# delete duplicate options
OPTIONS=($(echo "${OPTIONS[@]}" | tr ' ' '\n' | sort -u | tr '\n' ' '))

docker-compose --file dev/docker-compose.yml --env-file dev/.env --project-name ${PROJECT_NAME} up ${OPTIONS[@]}
