#!/usr/bin/env bash

if [ -z "$CI" ]
then
  set -e
  set -o pipefail
fi

CODE_DIRECOTRY='src/'

SCRIPT_DIR="$(dirname $(realpath "$0"))"

source "$SCRIPT_DIR/../../../packages/bash/ci_utils.sh"

cd "$SCRIPT_DIR/../"

ci-setup "$SCRIPT_DIR"

check-conflicts

commented-code "$CODE_DIRECOTRY"

file-class-name "$CODE_DIRECOTRY"

multi-classes "$CODE_DIRECOTRY"

coding-standars

unused-packages --excludePackage=ramsey/uuid

find-transitive-depndencies

find-magic-numbers -- "$CODE_DIRECOTRY"

find-copy-pasted-code "$CODE_DIRECOTRY"

static-analysis
print_separator 'validate doctrine schema'

if [ -z "$CI" ]
then
  vendor/bin/doctrine orm:validate-schema
else
  vendor/bin/doctrine orm:validate-schema --skip-sync
fi

check_exit_status $?
print_separator 'unit tests'

vendor/bin/phpunit $CODE_DIRECOTRY

check_exit_status $?

remake-autoloader

exit $EXIT_STATUS
