#!/usr/bin/env bash

if [ -z "$CI" ]
then
  set -e
  set -o pipefail
fi

CODE_DIRECOTRY='app/'

SCRIPT_DIR="$(dirname "$0")"

source "$SCRIPT_DIR/../../../packages/bash/utils.sh"

cd "$SCRIPT_DIR/../"

composer install

check_exit_status $?
print_separator

ecs

check_exit_status $?
print_separator

composer-unused

# check_exit_status $?
# print_separator

# composer-require-checker

check_exit_status $?
print_separator

phpmnd \
  --strings \
  --include-numeric-string \
  -- $CODE_DIRECOTRY

check_exit_status $?
print_separator

phpcpd $CODE_DIRECOTRY

check_exit_status $?
print_separator

psalm \
  --threads=4 \
  --no-cache

check_exit_status $?
print_separator

# vendor/bin/phpunit $CODE_DIRECOTRY

# check_exit_status "$UNIT_TESTS_STATUS"

if [ "$EXIT_STATUS" != "0" ]
then
  exit 1
fi
