#!/usr/bin/env bash

if [ -z "$CI" ]
then
  set -e
  set -o pipefail
fi

CODE_DIRECOTRY='app/'

SCRIPT_DIR="$(dirname $(realpath "$0"))"

source "$SCRIPT_DIR/../../../packages/bash/ci_utils.sh"

cd "$SCRIPT_DIR/../"

ci-setup "$SCRIPT_DIR"

check-conflicts

commented-code "$CODE_DIRECOTRY"

file-class-name "$CODE_DIRECOTRY"

multi-classes "$CODE_DIRECOTRY"

check-var-dump

coding-standars

unused-packages --excludePackage=consultorios/rest-framework

find-transitive-depndencies

find-magic-numbers -- $CODE_DIRECOTRY

find-copy-pasted-code "$CODE_DIRECOTRY"

static-analysis

# vendor/bin/phpunit $CODE_DIRECOTRY

# check_exit_status "$UNIT_TESTS_STATUS"

remake-autoloader

exit $EXIT_STATUS
