#!/usr/bin/env bash


CODE_DIRECOTRY='app/'

SCRIPT_DIR="$(dirname "$(realpath "$0")")"

# shellcheck disable=SC2034
NAMESPACE="$(basename "$(realpath "$SCRIPT_DIR/../")")"
# shellcheck source=/dev/null
source "$SCRIPT_DIR/../../../packages/bash/ci_utils.sh"

# shellcheck source=/dev/null
source "$SCRIPT_DIR/../../../packages/bash/php_utils.sh"

cd "$SCRIPT_DIR/../" || exit

php-ci-setup "$SCRIPT_DIR"

check-conflicts &

commented-code "$CODE_DIRECOTRY" &

file-class-name "$CODE_DIRECOTRY" &

multi-classes "$CODE_DIRECOTRY" &

check-var-dump &

coding-standars &

unused-packages &

find-transitive-depndencies &

find-magic-numbers -- "$CODE_DIRECOTRY" &

find-copy-pasted-code "$CODE_DIRECOTRY" &

static-analysis &

wait

remake-autoloader

show_summary

exit "$EXIT_STATUS"
