#!/usr/bin/env bash

if [ -z "$1" ];
    then
    PORT="8080"
else
    PORT="$1"
fi

SCRIPT_DIR=`dirname $0`

cd "$SCRIPT_DIR/../"

composer install

php -S localhost:$PORT -t "$SCRIPT_DIR/../public" "$SCRIPT_DIR/../public/dev-server.php"
