#!/usr/bin/env bash

SCRIPT_DIR="$(dirname "$(realpath "$0")")"

source "$SCRIPT_DIR/../../../packages/bash/php_utils.sh"

composer_setup \
  "$SCRIPT_DIR/../" \
  install

"$(dirname "$0")/../../../Core/Agendas/scripts/setup"
