#!/usr/bin/env bash

SCRIPT_DIR="$(dirname "$(realpath "$0")")"


# shellcheck source=/dev/null
source "$SCRIPT_DIR/../../../packages/bash/ci_utils.sh"
# shellcheck source=/dev/null
source "$SCRIPT_DIR/../../../packages/bash/php_utils.sh"

php-ci-setup "$SCRIPT_DIR"

if [ "$1" = "coverage-serve" ]
then
  php -S localhost:"${2:-8080}" -t phpunit-coverage

  exit
fi

phpunit \
  --prepend /root/.composer/vendor/autoload.php \
  --coverage-text \
  --coverage-html phpunit-coverage\
  "$@"
