#!/usr/bin/env bash

function setup-all() {
  local ORIGINAL_DIR
  ORIGINAL_DIR="$(realpath "$(pwd -P)")"

  local SCRIPT_DIR
  SCRIPT_DIR="$(dirname "$(realpath "$0")")"

  local ROOT_FOLDER
  ROOT_FOLDER="$SCRIPT_DIR/.."

  cd "$ROOT_FOLDER" || exit

  lefthook install

  "$ROOT_FOLDER/Core/Agendas/scripts/setup" &
  "$ROOT_FOLDER/Core/Common/scripts/setup" &
  "$ROOT_FOLDER/packages/php/ORM/scripts/setup" &
  "$ROOT_FOLDER/packages/php/RESTFramework/scripts/setup" &
  "$ROOT_FOLDER/WebApp/backend/scripts/setup" &
  "$ROOT_FOLDER/WebApp/frontend/scripts/setup" &

  wait

  cd "$ORIGINAL_DIR" || exit
}

setup-all
