#!/usr/bin/env bash

lefthook install

SCRIPT_DIR="$(dirname $(realpath "$0"))"

ROOT_FOLDER="$SCRIPT_DIR/.."

"$ROOT_FOLDER/Core/Agendas/scripts/setup"
"$ROOT_FOLDER/Core/Common/scripts/setup"
"$ROOT_FOLDER/packages/php/ORM/scripts/setup"
"$ROOT_FOLDER/packages/php/RESTFramework/scripts/setup"
"$ROOT_FOLDER/WebApp/backend/scripts/setup"
"$ROOT_FOLDER/WebApp/frontend/scripts/setup"
