on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
    paths:
      - 'Core/Agendas/**'
      - 'packages/bash/**'
  pull_request:
    types:
      - opened
      - edited
      - reopened
    paths:
      - 'Core/Agendas/**'
      - 'packages/bash/**'

jobs:
  continuous_integration:
    runs-on: ubuntu-latest
    name: Integración continua para Core/Agendas
    container:
      image: ghcr.io/iyaki/consultorios-ci-php:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - name: Cache composer cache
        id: cache-composer-cache
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache
          key: composer-cache-${{ hashFiles('.github/.cache-version') }}

      - name: Cache composer packages
        id: cache-composer-packages-agendas
        uses: actions/cache@v3
        env:
          cache-name: composer-agendas
        with:
          path: ./Core/Agendas/vendor
          key: ${{ env.cache-name }}-${{ hashFiles('.github/.cache-version') }}-${{ hashFiles('Core/Agendas/composer.json') }}
          restore-keys: ${{ env.cache-name }}-${{ hashFiles('.github/.cache-version') }}-

      - name: Validaciones
        run: Core/Agendas/scripts/check
