on:
  push:
    paths:
      - 'Core/Common/**'

jobs:
  continuous_integration:
    runs-on: ubuntu-latest
    name: Integración continua para Core/Common
    container:
      image: ghcr.io/iyaki/consultorios-ci-php:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - name: Validaciones
        run: Core/Common/scripts/check
