on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
    paths:
      - 'packages/php/RESTFramework/**'
      - 'packages/bash/**'
  pull_request:
    types:
      - opened
      - edited
      - reopened
    paths:
      - 'packages/php/RESTFramework/**'
      - 'packages/bash/**'

jobs:
  continuous_integration:
    runs-on: ubuntu-latest
    name: Integración continua para RESTFramework
    container:
      image: ghcr.io/iyaki/consultorios-ci-php:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - name: Cache composer cache
        id: cache-composer-cache
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache
          key: composer-cache
          restore-keys: |
            composer-cache

      - name: Cache composer packages
        id: cache-composer-packages-restframework
        uses: actions/cache@v3
        with:
          path: vendor
          key: composer-restframework
          restore-keys: |
            composer-restframework

      - name: Validaciones
        run: packages/php/RESTFramework/scripts/check

      - name: Averiguaciones
        run: |
          pwd
          ls -la
          echo "$HOME"
