on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
    paths:
      - 'packages/php/RESTFramework/**'
      - 'packages/bash/**'
  pull_request:
    types:
      - opened
      - edited
      - reopened
    paths:
      - 'packages/php/RESTFramework/**'
      - 'packages/bash/**'

jobs:
  continuous_integration:
    runs-on: ubuntu-latest
    name: Integración continua para RESTFramework
    container:
      image: ghcr.io/iyaki/consultorios-ci-php:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - name: Cache composer packages
        id: cache-composer
        uses: actions/cache@v3
        env:
          cache-name: cache-composer-packages
        with:
          path: ./vendor
          key: composer
          restore-keys: |
            composer

      - name: Validaciones
        run: packages/php/RESTFramework/scripts/check
