on:
  push:
    paths:
      - 'deploy/Dockerfile'
  pull_request:
    types:
      - opened
      - edited
      - reopened

jobs:
  release_ci_image:
    runs-on: ubuntu-latest
    name: Release image to the CI environment to the Github container registry
    steps:
      -  uses: actions/checkout@v2

      - name: Build image
        run: |
          DOCKER_BUILDKIT=1 docker build \
            --progress plain \
            --target php-ci \
            --tag ghcr.io/iyaki/consultorios-ci-php:latest \
            deploy/

      - name: Login into ghcr.io
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: docker push ghcr.io/iyaki/consultorios-ci-php:latest
