on:
  push:
    paths:
      - 'deploy/Dockerfile'

jobs:
  release_ci_image:
    runs-on: ubuntu-latest
    name: Release image to the CI environment to the Github container registry
    steps:
      -  uses: actions/checkout@v3

      - name: Build ci-php image
        run: |
          DOCKER_BUILDKIT=1 docker build \
            --progress plain \
            --target php-ci \
            --tag ghcr.io/iyaki/consultorios-ci-php:latest \
            deploy/

      - name: Build ci-nodejs image
        run: |
          DOCKER_BUILDKIT=1 docker build \
            --progress plain \
            --target node-runtime \
            --tag ghcr.io/iyaki/consultorios-ci-nodejs:latest \
            deploy/

      - name: Login into ghcr.io
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push ci-php image
        run: docker push ghcr.io/iyaki/consultorios-ci-php:latest

      - name: Push ci-nodejs image
        run: docker push ghcr.io/iyaki/consultorios-ci-nodejs:latest
