on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
    paths:
      - 'deploy/Dockerfile'
      - 'deploy/dev/packages/*'
      - 'deploy/dev/bin/*'

jobs:
  release_ci_image:
    runs-on: ubuntu-latest
    name: Release images of the CI environments to the Github container registry
    steps:

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      -  uses: actions/checkout@v3

      - name: Load .env
        run: |
          . deploy/dev/.env
          echo "PHP_VERSION=${PHP_VERSION}" >> "$GITHUB_ENV"

      - name: Build and push ci-php image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: deploy/Dockerfile
          target: php-ci
          build-args: PHP_VERSION=${{ env.PHP_VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          tags: ghcr.io/iyaki/consultorios-ci-php:latest

      - name: Build and push ci-nodejs image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: deploy/Dockerfile
          target: node-runtime
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          tags: ghcr.io/iyaki/consultorios-ci-nodejs:latest
