on:
  push:
    paths:
      - 'WebApp/backend/**'

jobs:
  continuous_integration:
    runs-on: ubuntu-latest
    name: Integración continua para WebApp/backend
    container:
      image: ghcr.io/iyaki/consultorios-ci-php:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - name: Validaciones
        run: pwd && ls -lah && WebApp/backend/scripts/check
