on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
    paths:
      - 'WebApp/backend/**'
      - 'packages/bash/**'
  pull_request:
    types:
      - opened
      - edited
      - reopened
    paths:
      - 'WebApp/backend/**'
      - 'packages/bash/**'

jobs:
  continuous_integration:
    runs-on: ubuntu-latest
    name: Integración continua para WebApp/backend
    container:
      image: ghcr.io/iyaki/consultorios-ci-php:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - name: Cache composer cache
        id: cache-composer-cache
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache
          key: composer-cache
          restore-keys: composer-cache

      - name: Cache composer packages
        id: cache-composer-packages-webapp-backend
        uses: actions/cache@v3
        with:
          path: ./WebApp/backend/vendor
          key: composer-webapp-backend
          restore-keys: composer-webapp-backend

      - name: Validaciones
        run: WebApp/backend/scripts/check
