on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
    paths:
      - 'WebApp/frontend/**'
      - 'packages/bash/**'
  pull_request:
    types:
      - opened
      - edited
      - reopened
    paths:
      - 'WebApp/frontend/**'
      - 'packages/bash/**'

jobs:
  continuous_integration:
    runs-on: ubuntu-latest
    name: Integración continua para WebApp/frontend
    container:
      image: ghcr.io/iyaki/consultorios-ci-nodejs:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - name: Cache npm cache
        id: cache-npm-cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-cache
          restore-keys: npm-cache

      - name: Cache node packages
        id: cache-node-packages-webapp-frontend
        uses: actions/cache@v3
        with:
          path: ./WebApp/frontend/node_modules
          key: composer-webapp-frontend
          restore-keys: composer-webapp-frontend

      - name: Validaciones
        run: WebApp/frontend/scripts/check
